USE [master]
GO

/****** Object:  Database [dupe_files]    Script Date: 2/11/2023 9:44:19 PM ******/
DROP DATABASE [dupe_files]
GO

/****** Object:  Database [dupe_files]    Script Date: 2/11/2023 9:44:19 PM ******/
CREATE DATABASE [dupe_files]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'dupe_files', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\dupe_files.mdf' , SIZE = 8192KB , MAXSIZE = 10240000KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'dupe_files_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\dupe_files_log.ldf' , SIZE = 8192KB , MAXSIZE = 10240000KB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dupe_files].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [dupe_files] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [dupe_files] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [dupe_files] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [dupe_files] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [dupe_files] SET ARITHABORT OFF 
GO

ALTER DATABASE [dupe_files] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [dupe_files] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [dupe_files] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [dupe_files] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [dupe_files] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [dupe_files] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [dupe_files] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [dupe_files] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [dupe_files] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [dupe_files] SET  DISABLE_BROKER 
GO

ALTER DATABASE [dupe_files] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [dupe_files] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [dupe_files] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [dupe_files] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [dupe_files] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [dupe_files] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [dupe_files] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [dupe_files] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [dupe_files] SET  MULTI_USER 
GO

ALTER DATABASE [dupe_files] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [dupe_files] SET DB_CHAINING OFF 
GO

ALTER DATABASE [dupe_files] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [dupe_files] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [dupe_files] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [dupe_files] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [dupe_files] SET QUERY_STORE = ON
GO

ALTER DATABASE [dupe_files] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [dupe_files] SET  READ_WRITE 
GO


